Two Bugs Fixed
at-internship/StoriesAPI pull request #48
Opened 2020-04-20 22:38 UTC by Gabriel-hcd

Bugs when story empty fixed and when task don´t belong to the story

2020-04-20 22:51 UTC, VictorMunguiaEnciso submitted a review, later dismissed

2020-04-20 23:01 UTC, apokochito commented on src/test/java/com/stories/service/ServiceTests.java
> +			.thenReturn(Boolean.TRUE);
Could you please use Constant class instead of the value directly?

2020-04-20 23:01 UTC, apokochito commented on src/test/java/com/stories/service/ServiceTests.java
> +			.thenReturn(Boolean.TRUE);
Could you please use Constant class instead of the value directly?

2020-04-20 23:02 UTC, apokochito commented on src/test/java/com/stories/service/ServiceTests.java
> +		TaskModel testingTask = testUtils.getDummyTaskModel();
Could you please use the testUtils object directly?

2020-04-20 23:04 UTC, apokochito commented on src/test/java/com/stories/service/ServiceTests.java
>  		taskModel.set_id("5e8dc1ba4ce33c0efc555845");
Can we move this into TestUtils class? Or use a similar object from there?

2020-04-21 13:46 UTC, VictorMunguiaEnciso requested changes

2020-04-21 13:46 UTC, VictorMunguiaEnciso commented on src/test/java/com/stories/service/ServiceTests.java
> +        .thenReturn(Boolean.FALSE);
Can you use a constant class for this value too ?

2020-04-21 13:46 UTC, VictorMunguiaEnciso commented on src/test/java/com/stories/service/ServiceTests.java
> +		assertEquals("5e8dc1ba4ce33c0efc555845", testUtils.getDummyTaskModel().get_id());
For this asserEquals too, could you please use a constant value for this  ?

2020-04-21 15:39 UTC, VictorMunguiaEnciso approved these changes

2020-04-21 16:41 UTC, soydianapinto approved these changes

2020-04-21 16:42 UTC, merged