Feature/kgn post delete by end point
at-internship/StoriesAPI pull request #6
Opened 2020-03-12 01:39 UTC by Armandosz117

Fixed code review commit

2020-03-12 23:36 UTC, at-internship requested changes

2020-03-12 23:36 UTC, Internship4thSource commented on src/main/java/com/stories/domain/StoryDomain.java
> +	private List<String> history;
Create a no-args constructor to initialize the history List.

2020-03-12 23:36 UTC, Internship4thSource commented on src/main/java/com/stories/domain/StoryDomain.java
> +@NoArgsConstructor
Remove this annotation, it's already added when using @Data.

2020-03-12 23:36 UTC, Internship4thSource commented on src/main/java/com/stories/service/StoryServiceImpl.java
> +		if (test == true) {
No need of ==. If 'test' is boolean, you can leave it like  `if (test) `.

2020-03-12 23:59 UTC, soydianapinto approved these changes

2020-03-13 00:02 UTC, at-internship approved these changes

2020-03-13 00:03 UTC, merged